// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPidRUFZOwCDRtahrImDPOViBg4BqfdbI',
    appId: '1:5296069020:web:6c8b99f8b95552fd815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    authDomain: 'shoezy-29a92.firebaseapp.com',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    measurementId: 'G-EF5N84NBR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALACy2iDLSuGFEaCzzqEkVJle7-UTDmV0',
    appId: '1:5296069020:android:0923b5ef9ba95b89815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp8msAgZHc9Ue8YOdW5jghNdrewG4X9QY',
    appId: '1:5296069020:ios:636f15f8d1ca5dd8815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    androidClientId: '5296069020-nd3i5l2uns14ouud6h20mrpv4gecr6cd.apps.googleusercontent.com',
    iosClientId: '5296069020-v417o4tqfd9v5980v2hb4p29g81f68al.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp8msAgZHc9Ue8YOdW5jghNdrewG4X9QY',
    appId: '1:5296069020:ios:636f15f8d1ca5dd8815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    androidClientId: '5296069020-nd3i5l2uns14ouud6h20mrpv4gecr6cd.apps.googleusercontent.com',
    iosClientId: '5296069020-v417o4tqfd9v5980v2hb4p29g81f68al.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPidRUFZOwCDRtahrImDPOViBg4BqfdbI',
    appId: '1:5296069020:web:c6ecb1595d37efd9815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    authDomain: 'shoezy-29a92.firebaseapp.com',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    measurementId: 'G-CEQDNH0B0Q',
  );
}
