// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPidRUFZOwCDRtahrImDPOViBg4BqfdbI',
    appId: '1:5296069020:web:024f45edeb1bad02815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    authDomain: 'shoezy-29a92.firebaseapp.com',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    measurementId: 'G-1LDREP9G4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALACy2iDLSuGFEaCzzqEkVJle7-UTDmV0',
    appId: '1:5296069020:android:d29349512110ae3a815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp8msAgZHc9Ue8YOdW5jghNdrewG4X9QY',
    appId: '1:5296069020:ios:f3c7597827b7abea815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    iosBundleId: 'com.example.shoezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp8msAgZHc9Ue8YOdW5jghNdrewG4X9QY',
    appId: '1:5296069020:ios:f3c7597827b7abea815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    iosBundleId: 'com.example.shoezy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPidRUFZOwCDRtahrImDPOViBg4BqfdbI',
    appId: '1:5296069020:web:024f45edeb1bad02815059',
    messagingSenderId: '5296069020',
    projectId: 'shoezy-29a92',
    authDomain: 'shoezy-29a92.firebaseapp.com',
    storageBucket: 'shoezy-29a92.firebasestorage.app',
    measurementId: 'G-1LDREP9G4G',
  );
}
